import _Button from "./shared/Button.jsx";
import _CheckBox from "./shared/Checkbox.jsx";
import _CopyText from "./shared/CopyText.jsx";
import _Select from "./shared/Select.jsx";
import _Textarea from "./shared/Textarea.jsx";
import _Input from "./shared/Input.jsx";
import _TableValue from "./widgets/Table/tableShared/TableValue.jsx";
import _Table from "./widgets/Table/Table.jsx";
import _TableRow from "./widgets/Table/tableShared/TableRow.jsx";
import _TableLabel from "./widgets/Table/tableShared/tableLabel.jsx";
import _TableBody from "./widgets/Table/tableShared/TableBody.jsx";
import _TableControls from "./widgets/Table/tableShared/TableControls.jsx";
import _EditModal from "./widgets/Table/tableShared/EditModal.jsx";
import _TableModalField from "./widgets/Table/tableShared/TableModalField.jsx";
import _CreateModal from "./widgets/Table/tableShared/CreateModal.jsx";
import _Field from "./widgets/Field/Field.jsx";

export const Button = _Button;
export const CheckBox = _CheckBox;
export const CopyText = _CopyText;
export const Select = _Select;
export const Textarea = _Textarea;
export const Input = _Input;

export const TableValue = _TableValue;
export const Table = _Table;
export const TableRow = _TableRow;
export const TableLabel = _TableLabel;
export const TableBody = _TableBody;
export const TableControls = _TableControls;
export const EditModal = _EditModal;
export const TableModalField = _TableModalField;
export const CreateModal = _CreateModal;
export const Field = _Field;
